name       : python-astroid
version    : 2.4.2
release    : 18
source     :
    - https://github.com/PyCQA/astroid/archive/astroid-2.4.2.tar.gz : 34d480d364dcf3e176bc302da56c5ef585ab45d4460f5a2761f960d2fd7b624c
homepage   : https://github.com/PyCQA/astroid
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A common base representation of python source code for pylint and other projects
description: |
    A common base representation of python source code for pylint and other projects
builddeps  :
    - numpy
    - python-lazy-object-proxy
    - python-nose
    - pytest-runner
    - python-typed-ast
    - python-wrapt
rundeps    :
    - python-lazy-object-proxy
    - python-six
    - python-typed-ast
    - python-wrapt
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
