name       : python-astroid
version    : 2.11.7
release    : 27
source     :
    - https://github.com/PyCQA/astroid/archive/refs/tags/v2.11.7.tar.gz : 16e49e6c9f95271e7a801a69ca9ba86a7c5651896c61c91dc5e87fc3e5de6819
homepage   : https://github.com/PyCQA/astroid
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A common base representation of python source code for pylint and other projects
description: |
    The aim of this module is to provide a common base representation of python source code. It is currently the library powering pylint's capabilities.
builddeps  :
    - numpy                    # check
    - python-lazy-object-proxy # check
    - python-nose              # check
    - python-pytest            # check
    - python-typing-extensions # remove when possible...
    - python-wrapt             # check
rundeps    :
    - python-lazy-object-proxy
    - python-six
    - python-typing-extensions # remove when possible...
    - python-wrapt
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
