name       : python-astroid
version    : 2.6.2
release    : 20
source     :
    - https://github.com/PyCQA/astroid/archive/refs/tags/v2.6.2.tar.gz : 0b146fca525affa936312de8e2e196e92562527f389fcd86f66bf1c8b5cd1a0e
homepage   : https://github.com/PyCQA/astroid
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A common base representation of python source code for pylint and other
    projects
description: |
    A common base representation of python source code for pylint and other projects
builddeps  :
    - numpy
    - python-lazy-object-proxy
    - python-nose
    - pytest-runner
    - python-typed-ast
    - python-typing-extensions # remove for 3.9
    - python-wrapt
rundeps    :
    - python-lazy-object-proxy
    - python-six
    - python-typed-ast
    - python-typing-extensions # remove for 3.9
    - python-wrapt
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
