name       : python-astroid
version    : 2.4.0
release    : 15
source     :
    - https://github.com/PyCQA/astroid/archive/astroid-2.4.0.tar.gz : 07b71790b68ddbad4754af6597af1b10bfb713edea7b305b602f8cce2746b458
homepage   : https://github.com/PyCQA/astroid
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A common base representation of python source code for pylint and other projects
description: |
    A common base representation of python source code for pylint and other projects
builddeps  :
    - numpy
    - python-lazy-object-proxy
    - python-nose
    - pytest-runner
    - python-typed-ast
    - python-wrapt
rundeps    :
    - python-lazy-object-proxy
    - python-six
    - python-typed-ast
    - python-wrapt
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
